### ISSUE TITLE
2Dゲームのカメラ設定

### ISSUE THREAD

**Issue by Zudies** [kmc-jp/puzzleGame2023#3]

**Comment by Zudies** [comment]
n622さんは#7 と一緒にすでに完成してくれました

**Comment by OsawaKousei** [comment]
確かに。
でもめっちゃ適当なんで、後々直さなくちゃいけなくなるかもです…

**Comment by Zudies** [comment]
プロジェクトの２D ゲーム対応の基本設定は足りなかったみたい。このissueをそのために再利用させていただきます
