### ISSUE TITLE
赤色のアニマの挙動を実装する

### ISSUE THREAD

**Issue by LosenkaNiya** [kmc-jp/puzzleGame2023#53]
- [ ] RedAnimaBehaviourコンポーネントを作成する
- [ ] Update内部で色固有の動きを実装する

**Comment by takikawauniv** [comment]
赤Animaの前後運動の動きのイメージがどのようなものか分からなかったので、とりあえず3種のコンポーネント
(RedAnimaBehaviourCF/RedAnimaBehaviourHF/RedAnimaBehaviourMP)を実装しました。

CF:周期ごとに右か左へ一定の力がかかります。
HF:生成位置から単振動をします。(中心の位置は固定です。)
MP:これだけaddForceではなくmovePositionで実装してあります。 生成位置から単振動で、他のオブジェクトから動きへの干渉を受けません。
