### ISSUE TITLE
Mirror導入

### ISSUE THREAD

**Issue by Zudies** [kmc-jp/puzzleGame2023#9]
Mirrorをプロジェクト内に導入＋初期化

**Comment by LosenkaNiya** [comment]
Mirror導入下での環境を作っておきます。
ブランチ名はnetworkとかでいいですか？

**Comment by Zudies** [comment]
できればもっと細かいブランチ名が欲しい。例えば「9-add-mirror-library」等、せめてissueの番号が入ったらそのブランチの詳細が分かりやすくなると思います。

**Comment by LosenkaNiya** [comment]
導入完了。
Mirror ver79.0.1
